server:
  port: 9200

temporary-file-path: ${java.io.tmpdir}
static-file-context:

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: localhost
    password: localhost
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  security:
    oauth2:
app:
  config:
    encryption: true

jwt:
  secret: customsecretkeycustomsecretkeycustomsecretkeycustomsecretkey
  expiration: 108000000 # 30분

crypto:
  aes:
    key: ASDF123456789012QWER123456789012
    iv: 1234567890123456

dunamnu:
  base-url: https://quotation-api-cdn.dunamu.com
  exchange-rate:
    uri: /v1/forex/recent?codes=FRX.KRWJPY,FRX.KRWUSD #TODO: URI/파라미터는 코드에서 관리
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type: trace
#          descriptor:
#            sql:
#              BasicBinder: trace
